[021] Passwort Generator L.P.
SpaTeamAcademy/Team_B pull request #18
Opened 2023-07-31 09:14 UTC by HornGabriel

021 - PW Generator - Grundfunktion (3 SP)

https://app.asana.com/0/1205072348884933/1205158446708989/f

2023-07-31 11:30 UTC, SpaTeamAcademy commented on passwort.js
> +    switch (charType) {
Was macht dieser switch?

2023-07-31 11:35 UTC, HornGabriel commented on passwort.js
> +    switch (charType) {
Ich habe hier eigentlich mehrere Switches eingebaut gehabt damit man wählen kann zwischen den Unterteilungen (kleinbuchstaben etc) ich habe die restlichen jedoch entfernt und hätte diese mit der nächsten Story eingearbeitet

2023-07-31 11:46 UTC, SpaTeamAcademy requested changes

2023-07-31 11:46 UTC, SpaTeamAcademy commented on passwort.js
> +    switch (charType) {
Grundsätzlich sollten keine Funktionen eingebaut werden, die nicht zur aktuellen Story gehören.
Auch sind schon Variablen vordefiniert und auskommentiert, die erst bei der nächsten Story relevant werden.
Daher sehe ich für Story 021 keine Funktionalität im switch.

2023-07-31 11:46 UTC, SpaTeamAcademy commented on passwort.js
> +   passwort += getRandomChar(kleinbuchstaben);
DRY-Prinzip: Diese Codezeile ist doppelt > Zeile 16

2023-07-31 11:50 UTC, HornGabriel commented on passwort.js
> +    switch (charType) {
Wie erwünscht werde ich die Änderungen vornehmen.

2023-07-31 12:16 UTC, SpaTeamAcademy commented
Bitte Merge Conflict lösen.

2023-07-31 12:27 UTC, SpaTeamAcademy approved these changes

2023-08-01 08:40 UTC, SpaTeamAcademy approved these changes

2023-08-01 08:40 UTC, merged